### ISSUE TITLE
¥转换工作不正常

### ISSUE THREAD

**Issue by Zonaldo7** [gimjin/banjiao#3]
使用vs code (Version: 1.85.1)插件，系统为mac 14.2.1, 使用过程中¥无法自动转换为$

**Comment by gimjin** [comment]
> 使用vs code (Version: 1.85.1)插件，系统为mac 14.2.1, 使用过程中¥无法自动转换为$

先确认状态栏是否显示 “半角” （Alt+b 可以开关，如果关闭会出现 “全角”）

依然出现此缺陷我需要你的帮忙，我的 Mac 和你的版本不太一样，目前没办法复现。 能帮忙看一下吗？

操作步骤：
1. 下载banjiao工程代码
2. 打开 extension.js 文件，第56行打个断点（数字前面点出来红色的点）
3. F5 运行一下，你会发现会打开新的 vscode 窗口，等一会儿半角会被加载
4. 输入 ￥ 符号，此时断点会启动，看一下 halfChar 的值（附件是正常情况下的效果）
5. 帮忙看一下哪个逻辑出了问题

![image](https://github.com/gimjin/banjiao/assets/6750397/e669b822-0086-4419-8267-69b6b0914da0)

**Comment by Conless** [comment]
我也出现了这样的问题，插件版本 1.2.9，macOS 14.0

**Comment by gimjin** [comment]
@Conless 非常感谢 PR
