### ISSUE TITLE
请求适配Jupyter Notebooke

### ISSUE THREAD

**Issue by Ricci084** [gimjin/banjiao#4]
VSCode 内置的Jupyter Notebook里不能自动切换全角为半角，请求适配。

**Comment by gimjin** [comment]
> VSCode 内置的Jupyter Notebook里不能自动切换全角为半角，请求适配。

好的，我研究研究，从来没用过 Jupyter Notebook o(╥﹏╥)o

**Comment by gimjin** [comment]
> VSCode 内置的Jupyter Notebook里不能自动切换全角为半角，请求适配。

兄弟，已经适配了，升级最新版本吧。
